version: "2"
services: 
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        ports:
        - 27017:27017
        volumes:
        - ./data:/data/db
    digitalnotes:
        build: .
        restart: always
        container_name: digitalnotes
        depends_on:
        - mongodb
        ports:
        - 5000:5000
